### ISSUE TITLE
What does A, N, S, R, V, means?

### ISSUE THREAD

**Issue by Vamoss** [finnlp/synonyms#2]
I suppose:
```
a = adverb and adjective
n = noun
v = verb
s = ?
r = ?
```

**Comment by behzadmoradi** [comment]
n NOUN
v VERB
a ADJECTIVE
s ADJECTIVE SATELLITE **
r ADVERB

** Adjective satellites imposes additional commitments on top of the meaning of the central adjective, e.g. "arid" = "dry" + a particular context (i.e. climates)
