### ISSUE TITLE
Why n and v keys in the synonyms object and what they mean?

### ISSUE THREAD

**Issue by tanvir362** [finnlp/synonyms#4]

**Comment by Fiattarone** [comment]
Hi @tanvir362 

I'm new to this codebase but can answer that for you: 
"n" denotes synonyms of the noun form, whereas "v" denotes synonyms of the verb form.

**Comment by Fiattarone** [comment]
@alexcorvi if you don't mind, I'm going to produce a CODETOUR/README that should help close this issue in a separate PR.

**Comment by tanvir362** [comment]
Okay. Thanks for your effort @Fiattarone
